server:
  port: 18201
spring:
  application:
    name: service-hospital
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_hosp
    username: root
    password: 20020327
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://localhost:27017/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    top.integer.yygh.mapper: debug
